/*
  Темы оформления сайта.

  Каждая тема — это набор значений для тех же переменных, что заданы в
  css/style.css. Тема переключается в админке, выбор хранится в данных
  (settings.theme), а main.js подставляет значения в :root при загрузке.

  Кроме цветов темы задают и структурные вещи: шапка бывает светлой и
  тёмной, кнопка — сплошной и с переходом. Иначе при смене палитры шапка
  осталась бы от старой темы.

  Глубокие оттенки (--*-deep) подобраны так, чтобы белый текст на них
  читался: контраст не ниже 4.5. Это проверяется при сборке файла.
*/

const SITE_THEMES = [
  {
    "id": "dopamine",
    "name": "Дофаминовая",
    "note": "яркая и жизнерадостная — как сейчас",
    "swatch": [
      "#24b6f0",
      "#21c98d",
      "#ffcc33",
      "#ff5fa2"
    ],
    "vars": {
      "--primary": "#24b6f0",
      "--primary-deep": "#0b7fbd",
      "--primary-soft": "#e8f7fe",
      "--primary-line": "#bfe6f8",
      "--second": "#21c98d",
      "--second-deep": "#07805a",
      "--second-soft": "#e6faf1",
      "--second-line": "#bfead8",
      "--warm": "#ffcc33",
      "--warm-deep": "#a86b00",
      "--warm-soft": "#fff6dd",
      "--warm-line": "#f6e4ae",
      "--accent": "#ff5fa2",
      "--accent-deep": "#c9316f",
      "--white": "#ffffff",
      "--page": "#ffffff",
      "--surface": "#f4fbff",
      "--line": "#d7ecf7",
      "--ink": "#10222e",
      "--ink-soft": "#5b7482",
      "--dark": "#08222f",
      "--dark-2": "#103c52",
      "--hero-bg": "linear-gradient(165deg, var(--dark-2), var(--dark) 60%)",
      "--hero-ink": "var(--white)",
      "--hero-ink-soft": "#c7e9f7",
      "--hero-mark": "var(--warm)",
      "--hero-glow-1": "rgba(36, 182, 240, .55)",
      "--hero-glow-2": "rgba(33, 201, 141, .42)",
      "--footer-ink": "#a9cfe0",
      "--overlay": "rgba(8, 34, 47, .93)",
      "--chrome-bg": "rgba(255, 255, 255, .82)",
      "--btn-bg": "linear-gradient(120deg, var(--primary-deep), var(--second-deep))",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "linear-gradient(120deg, var(--second-deep), var(--primary-deep))",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--primary-soft), var(--second-soft))"
    }
  },
  {
    "id": "wildflower",
    "name": "Полевые цветы",
    "note": "пастель, кремовый фон — по подборке Даши",
    "swatch": [
      "#adbacb",
      "#a1ac4e",
      "#eec474",
      "#e5a39d"
    ],
    "vars": {
      "--primary": "#adbacb",
      "--primary-deep": "#5e7695",
      "--primary-soft": "#f5f6f7",
      "--primary-line": "#d7dbe0",
      "--second": "#a1ac4e",
      "--second-deep": "#6f7736",
      "--second-soft": "#f7f8f4",
      "--second-line": "#e1e3d3",
      "--warm": "#eec474",
      "--warm-deep": "#96690f",
      "--warm-soft": "#faf7f2",
      "--warm-line": "#ece1cb",
      "--accent": "#e5a39d",
      "--accent-deep": "#c0453a",
      "--white": "#ffffff",
      "--page": "#f9faec",
      "--surface": "#ffffff",
      "--line": "#e0e4cf",
      "--ink": "#2f3328",
      "--ink-soft": "#6d7263",
      "--dark": "#333a29",
      "--dark-2": "#4c5639",
      "--hero-bg": "linear-gradient(170deg, var(--primary-soft), var(--page) 48%, var(--warm-soft))",
      "--hero-ink": "var(--ink)",
      "--hero-ink-soft": "var(--ink-soft)",
      "--hero-mark": "var(--second-deep)",
      "--hero-glow-1": "rgba(229, 163, 157, .45)",
      "--hero-glow-2": "rgba(173, 186, 203, .55)",
      "--footer-ink": "#cdd3b6",
      "--overlay": "rgba(38, 43, 32, .94)",
      "--chrome-bg": "rgba(249, 250, 236, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--accent), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "quartz",
    "name": "Розовый кварц",
    "note": "пыльная роза и шалфей, мягко и женственно",
    "swatch": [
      "#d4849e",
      "#9db8a8",
      "#f0c9a0",
      "#e0608e"
    ],
    "vars": {
      "--primary": "#d4849e",
      "--primary-deep": "#c24f74",
      "--primary-soft": "#f8f4f5",
      "--primary-line": "#e6d1d8",
      "--second": "#9db8a8",
      "--second-deep": "#5a7c68",
      "--second-soft": "#f5f7f6",
      "--second-line": "#d8dfdb",
      "--warm": "#f0c9a0",
      "--warm-deep": "#a9641b",
      "--warm-soft": "#faf6f3",
      "--warm-line": "#ebdccc",
      "--accent": "#e0608e",
      "--accent-deep": "#d83570",
      "--white": "#ffffff",
      "--page": "#fefdfe",
      "--surface": "#ffffff",
      "--line": "#ebe0e4",
      "--ink": "#2b171e",
      "--ink-soft": "#825e6a",
      "--dark": "#250e15",
      "--dark-2": "#461b29",
      "--hero-bg": "linear-gradient(170deg, var(--primary-soft), var(--page) 48%, var(--warm-soft))",
      "--hero-ink": "var(--ink)",
      "--hero-ink-soft": "var(--ink-soft)",
      "--hero-mark": "var(--second-deep)",
      "--hero-glow-1": "rgba(224, 96, 142, .45)",
      "--hero-glow-2": "rgba(212, 132, 158, .5)",
      "--footer-ink": "#d6c2c8",
      "--overlay": "rgba(37, 14, 21, .94)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "mint",
    "name": "Мятная свежесть",
    "note": "мята и морская вода, свежо и чисто",
    "swatch": [
      "#5cc0b0",
      "#7bb8d9",
      "#f2d59b",
      "#f08a8a"
    ],
    "vars": {
      "--primary": "#5cc0b0",
      "--primary-deep": "#338376",
      "--primary-soft": "#f4f8f8",
      "--primary-line": "#d2e5e2",
      "--second": "#7bb8d9",
      "--second-deep": "#2f7ca5",
      "--second-soft": "#f3f7f9",
      "--second-line": "#cfdfe7",
      "--warm": "#f2d59b",
      "--warm-deep": "#996c14",
      "--warm-soft": "#faf7f2",
      "--warm-line": "#ece1cb",
      "--accent": "#f08a8a",
      "--accent-deep": "#e32727",
      "--white": "#ffffff",
      "--page": "#fdfefe",
      "--surface": "#ffffff",
      "--line": "#e0ebe9",
      "--ink": "#172b28",
      "--ink-soft": "#5e827c",
      "--dark": "#0e2521",
      "--dark-2": "#1b463f",
      "--hero-bg": "linear-gradient(170deg, var(--primary-soft), var(--page) 48%, var(--warm-soft))",
      "--hero-ink": "var(--ink)",
      "--hero-ink-soft": "var(--ink-soft)",
      "--hero-mark": "var(--second-deep)",
      "--hero-glow-1": "rgba(240, 138, 138, .45)",
      "--hero-glow-2": "rgba(92, 192, 176, .5)",
      "--footer-ink": "#c2d6d3",
      "--overlay": "rgba(14, 37, 33, .94)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "nude",
    "name": "Пудра и кофе",
    "note": "нюд и кофе — салонная классика",
    "swatch": [
      "#b89b8a",
      "#8c7160",
      "#e8c9a8",
      "#c98a7a"
    ],
    "vars": {
      "--primary": "#b89b8a",
      "--primary-deep": "#926e59",
      "--primary-soft": "#f7f6f5",
      "--primary-line": "#e1dad6",
      "--second": "#8c7160",
      "--second-deep": "#8c7160",
      "--second-soft": "#f7f6f5",
      "--second-line": "#dfdad7",
      "--warm": "#e8c9a8",
      "--warm-deep": "#a3692b",
      "--warm-soft": "#f9f6f3",
      "--warm-line": "#e8dccf",
      "--accent": "#c98a7a",
      "--accent-deep": "#b35e49",
      "--white": "#ffffff",
      "--page": "#fefefd",
      "--surface": "#ffffff",
      "--line": "#e8e5e3",
      "--ink": "#2b1f17",
      "--ink-soft": "#826c5e",
      "--dark": "#25170e",
      "--dark-2": "#462b1b",
      "--hero-bg": "linear-gradient(170deg, var(--primary-soft), var(--page) 48%, var(--warm-soft))",
      "--hero-ink": "var(--ink)",
      "--hero-ink-soft": "var(--ink-soft)",
      "--hero-mark": "var(--second-deep)",
      "--hero-glow-1": "rgba(201, 138, 122, .45)",
      "--hero-glow-2": "rgba(184, 155, 138, .5)",
      "--footer-ink": "#d6c9c2",
      "--overlay": "rgba(37, 23, 14, .94)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "lavender",
    "name": "Лаванда",
    "note": "лавандовый с зеленью и сливочным",
    "swatch": [
      "#a99ad4",
      "#b5c9a0",
      "#f5dfa0",
      "#d99ac4"
    ],
    "vars": {
      "--primary": "#a99ad4",
      "--primary-deep": "#7e68bf",
      "--primary-soft": "#f5f4f8",
      "--primary-line": "#d7d3e4",
      "--second": "#b5c9a0",
      "--second-deep": "#647e48",
      "--second-soft": "#f6f7f5",
      "--second-line": "#dbe1d5",
      "--warm": "#f5dfa0",
      "--warm-deep": "#916f0f",
      "--warm-soft": "#faf8f2",
      "--warm-line": "#ede4ca",
      "--accent": "#d99ac4",
      "--accent-deep": "#bc4c97",
      "--white": "#ffffff",
      "--page": "#fefdfe",
      "--surface": "#ffffff",
      "--line": "#e3e1ea",
      "--ink": "#1c172b",
      "--ink-soft": "#685e82",
      "--dark": "#140e25",
      "--dark-2": "#261b46",
      "--hero-bg": "linear-gradient(170deg, var(--primary-soft), var(--page) 48%, var(--warm-soft))",
      "--hero-ink": "var(--ink)",
      "--hero-ink-soft": "var(--ink-soft)",
      "--hero-mark": "var(--second-deep)",
      "--hero-glow-1": "rgba(217, 154, 196, .45)",
      "--hero-glow-2": "rgba(169, 154, 212, .5)",
      "--footer-ink": "#c7c2d6",
      "--overlay": "rgba(20, 14, 37, .94)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "sunset",
    "name": "Тёплый закат",
    "note": "терракота и янтарь на тёмном",
    "swatch": [
      "#e08a5c",
      "#d9a05c",
      "#f5c98a",
      "#c95c7a"
    ],
    "vars": {
      "--primary": "#e08a5c",
      "--primary-deep": "#bc5924",
      "--primary-soft": "#f9f5f3",
      "--primary-line": "#ead7cd",
      "--second": "#d9a05c",
      "--second-deep": "#a06825",
      "--second-soft": "#f9f6f3",
      "--second-line": "#e9dcce",
      "--warm": "#f5c98a",
      "--warm-deep": "#a5670e",
      "--warm-soft": "#faf7f2",
      "--warm-line": "#eddfc9",
      "--accent": "#c95c7a",
      "--accent-deep": "#c44d6d",
      "--white": "#ffffff",
      "--page": "#fefefd",
      "--surface": "#ffffff",
      "--line": "#ede3de",
      "--ink": "#2b1e17",
      "--ink-soft": "#826b5e",
      "--dark": "#2a1a20",
      "--dark-2": "#5b3026",
      "--hero-bg": "linear-gradient(165deg, var(--dark-2), var(--dark) 60%)",
      "--hero-ink": "var(--white)",
      "--hero-ink-soft": "#f0d5c0",
      "--hero-mark": "var(--warm)",
      "--hero-glow-1": "rgba(224, 138, 92, .5)",
      "--hero-glow-2": "rgba(201, 92, 122, .38)",
      "--footer-ink": "#d9b9a5",
      "--overlay": "rgba(42, 26, 32, .93)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  },
  {
    "id": "graphite",
    "name": "Графит",
    "note": "строгая серо-графитовая с медным акцентом",
    "swatch": [
      "#6b7280",
      "#9ca3af",
      "#d4b483",
      "#d97757"
    ],
    "vars": {
      "--primary": "#6b7280",
      "--primary-deep": "#6b7280",
      "--primary-soft": "#f6f6f7",
      "--primary-line": "#d9dbdd",
      "--second": "#9ca3af",
      "--second-deep": "#6d7787",
      "--second-soft": "#f6f6f7",
      "--second-line": "#d9dbde",
      "--warm": "#d4b483",
      "--warm-deep": "#956e34",
      "--warm-soft": "#f8f7f4",
      "--warm-line": "#e6ddd1",
      "--accent": "#d97757",
      "--accent-deep": "#c2512c",
      "--white": "#ffffff",
      "--page": "#fdfefe",
      "--surface": "#ffffff",
      "--line": "#e4e5e7",
      "--ink": "#171e2b",
      "--ink-soft": "#5e6a82",
      "--dark": "#0e1625",
      "--dark-2": "#1b2946",
      "--hero-bg": "linear-gradient(165deg, var(--dark-2), var(--dark) 60%)",
      "--hero-ink": "var(--white)",
      "--hero-ink-soft": "#cfd7e8",
      "--hero-mark": "var(--warm)",
      "--hero-glow-1": "rgba(107, 114, 128, .5)",
      "--hero-glow-2": "rgba(156, 163, 175, .42)",
      "--footer-ink": "#b7c2d7",
      "--overlay": "rgba(14, 22, 37, .93)",
      "--chrome-bg": "rgba(255, 255, 255, .85)",
      "--btn-bg": "var(--primary-deep)",
      "--cta-bg": "var(--warm)",
      "--cta-ink": "var(--ink)",
      "--label-bg": "var(--second-deep)",
      "--avatar-bg": "linear-gradient(135deg, var(--primary), var(--second))",
      "--cases-bg": "linear-gradient(180deg, var(--warm-soft), var(--second-soft))"
    }
  }
];

const DEFAULT_THEME = "dopamine";

// Подставляет цвета темы в :root. Неизвестный id — молча берём тему по умолчанию.
function applyTheme(id, root) {
  const list = SITE_THEMES;
  const theme = list.find((t) => t.id === id) || list.find((t) => t.id === DEFAULT_THEME);
  if (!theme) return;
  const target = (root || document.documentElement).style;
  Object.keys(theme.vars).forEach((name) => target.setProperty(name, theme.vars[name]));
}

if (typeof module !== "undefined" && module.exports) module.exports = { SITE_THEMES, DEFAULT_THEME, applyTheme };
